### ISSUE TITLE
I try to compile this on Arduino 1.8.13 but can't link the arm_math.h functions

### ISSUE THREAD

**Issue by deftio** [arduino/ArduinoAI#3]
When I try to compile this it can't linke arm_rfft_init_q15.  How do I add that to nano BLE sketch / toolchain?

**Comment by thomasfischer089** [comment]
I have the same problem. Did you find a solution?
Best regards

**Comment by deftio** [comment]
If you use the online compiler from arduino.cc  then I got it to work but I can't get it to build on my laptop stand alone...

**Comment by thomasfischer089** [comment]
When you use the version 1.1.6 in the board manager than it works. Not with the 1.3.0

**Comment by deftio** [comment]
You're right I got 1.1.6 to work.  Thanks!

**Comment by thomasfischer089** [comment]
No problem.
Maybe someon find a fix in 1.3.0

**Comment by maxgerhardt** [comment]
Can you try 

https://github.com/DaleGia/Nano33BLESensor/issues/6#issuecomment-776717279

**Comment by carlosperate** [comment]
> If you use the online compiler from arduino.cc then I got it to work but I can't get it to build on my laptop stand alone...

Looks like the online compiler doesn't work these days either :/

**Comment by carlosperate** [comment]
`arm_math.h` has now been released as an Arduino library:
- https://github.com/arduino-libraries/Arduino_CMSIS-DSP
- https://github.com/arduino/ArduinoCore-mbed/issues/7#issuecomment-842179221

I'm currently having an issue compiling it with the "Arduino Mbed OS Nano Boards" core v2.1.0 and v2.0.0, once that is fixed we should have a simple way to compile this again: https://github.com/arduino/ArduinoCore-mbed/issues/228

------

Edit: Turns out the issue was due to using an older version of the IDE, after upgrading to v1.8.15 it compiled correctly 😃

**Comment by x5115x** [comment]
Install "Arduino_CMSIS-DSP" library will fix this error.

**Comment by deftio** [comment]
Closing this as its an old issue and fixes are mentioned in the thread.
